### ISSUE TITLE
Faulty aida-light server configuration

### ISSUE THREAD

**Issue by gingaz** [ChalithaUdara/Apache-Stanbol-Disambiguation-API#2]
Hi,

when I run server with mvn jetty:run-forked, the server startups, but is not accessible:
I get the following in the browser:
HTTP ERROR 404
Problem accessing /. Reason:
    Not Found

Any clue what is the issue?

Thanks,
Gin

**Comment by ChalithaUdara** [comment]
Hi,

What is the url you are accessing after starting the server ?
Urls should be http://{host}:{9090}/service/{end-point}
For example, you can try http://localhost:9090/service/example 

Thanks,
Chalitha

**Comment by ChalithaUdara** [comment]
Hi Gin,

can we close this issue ?

Thanks,
Chalitha

**Comment by gingaz** [comment]
Hi Chalitha,

yes please.
Apologies for not responding on time.

Cheers,
Gin

Best Regards,
Gintautas Sulskus

**Comment by ChalithaUdara** [comment]
Thank you !
